apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: nifi-ocp
  name: nifi-ocp
spec:
  nodeSelector:
  output:
    to:
      kind: ImageStreamTag
      name: "nifi-ocp:latest"
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
